use turbo mode for lookup plugins
ansible-collections/vmware.vmware_rest pull request #238
Opened 2021-08-03 15:20 UTC by abikouo

##### SUMMARY

use turbo mode for lookup plugins

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-08-09 08:22 UTC, abikouo commented
recheck

2021-08-11 11:03 UTC, Akasurde approved these changes

2021-08-11 11:21 UTC, alinabuzachis requested changes

2021-08-11 11:21 UTC, alinabuzachis commented on plugins/lookup/cluster_moid.py
> +        return [result]
@abikouo you are still returning a list.

2021-08-11 11:23 UTC, alinabuzachis requested changes

2021-08-11 11:23 UTC, alinabuzachis commented on plugins/lookup/datacenter_moid.py
> +        result = await Lookup.entry_point(terms, self._options)
Even here.

2021-08-11 11:25 UTC, alinabuzachis commented
@abikouo Thank you for working on this. The result is stil returned as a list.

2021-08-11 14:48 UTC, abikouo commented
> @abikouo Thank you for working on this. The result is stil returned as a list and it must be a string.

It is failing when I do not return a list, it seems that the result should be a list, otherwise when the option ``wantList`` is set to true the raw result is returned, otherwise the core engine will perform a join operation.

2021-08-11 14:52 UTC, alinabuzachis commented
> > @abikouo Thank you for working on this. The result is stil returned as a list and it must be a string.
> 
> It is failing when I do not return a list, it seems that the result should be a list, otherwise when the option `wantList` is set to true the raw result is returned, otherwise the core engine will perform a join operation.

We agreed to keep it as simple as possible https://github.com/ansible-collections/vmware.vmware_rest/pull/209#issuecomment-878365007 and have the result returned as a string, it doesn't make sense to have the result as a list because only one path is processed at time. If we want to get the moid from multiple paths we use a different approach (as @goneri explained).

2021-08-12 09:42 UTC, abikouo commented
> > > @abikouo Thank you for working on this. The result is stil returned as a list and it must be a string.
> > 
> > 
> > It is failing when I do not return a list, it seems that the result should be a list, otherwise when the option `wantList` is set to true the raw result is returned, otherwise the core engine will perform a join operation.
> 
> We agreed to keep it as simple as possible [#209 (comment)](https://github.com/ansible-collections/vmware.vmware_rest/pull/209#issuecomment-878365007) and have the result returned as a string. It doesn't make sense to have the result as a list because only one path is processed at time. If we want to get the moid from multiple paths we use a different approach (as @goneri explained). For this reason the result has been returned and documented as a string.

@alinabuzachis I got the point, but the result should be return as list, this is expected on ansible core otherwise when you set the option ``wantLIst`` to ``true`` it will not work, I think the confusion with the current version if that ``lookup.entry_point`` will return a string result, but when calling ``asyncio.gather`` this is wrapping the result into a list, do no hesitate if you have others questions

2021-08-12 11:01 UTC, alinabuzachis commented
> > > > @abikouo Thank you for working on this. The result is stil returned as a list and it must be a string.
> > > 
> > > 
> > > It is failing when I do not return a list, it seems that the result should be a list, otherwise when the option `wantList` is set to true the raw result is returned, otherwise the core engine will perform a join operation.
> > 
> > 
> > We agreed to keep it as simple as possible [#209 (comment)](https://github.com/ansible-collections/vmware.vmware_rest/pull/209#issuecomment-878365007) and have the result returned as a string. It doesn't make sense to have the result as a list because only one path is processed at time. If we want to get the moid from multiple paths we use a different approach (as @goneri explained). For this reason the result has been returned and documented as a string.
> 
> @alinabuzachis I got the point, but the result should be return as list, this is expected on ansible core otherwise when you set the option `wantLIst` to `true` it will not work, I think the confusion with the current version if that `lookup.entry_point` will return a string result, but when calling `asyncio.gather` this is wrapping the result into a list, do no hesitate if you have others questions

`asyncio.gather` was initially used when I supported a list of paths and then returned a list of MoIDs, but I then forgot to remove it. Even if using `wantLIst=true` won't make sense in our case because we have only one result, it makes sense your approach.

2021-08-12 11:02 UTC, alinabuzachis approved these changes

2021-08-12 11:43 UTC, merged