Cherry pick main 4.0.0 into stable-3
ansible-collections/vmware.vmware_rest pull request #517
Opened 2024-08-16 19:41 UTC by mikemorency

##### SUMMARY
This PR is cherry picking missing commits from main into stable-3 prior to the next 3.X release

##### ISSUE TYPE
- Backport

##### ADDITIONAL INFORMATION
Let me know if this is not how things are normally backported. As far as I can tell, these are commits that the backport-3 label was not applied to (or missed) but should be included in the next 3.x minor release

2024-08-17 12:47 UTC, mariolenz requested changes
#495 has been a breaking change that requires a new major version. We can't backport this.

2024-08-17 12:47 UTC, mariolenz commented on .github/workflows/sanity-tests.yaml
> -          - stable-2.14
breaking

2024-08-17 12:47 UTC, mariolenz commented on changelogs/fragments/492-remove-support-ansible-2-14.yml
> +  - Removing any support for ansible-core <=2.14
breaking

2024-08-17 12:47 UTC, mariolenz commented on README.md
> +This collection has been tested against following Ansible versions: **>=2.15.0**.
breaking

2024-08-17 12:47 UTC, mariolenz commented on meta/runtime.yml
> +requires_ansible: ">=2.15.0"
breaking

2024-08-17 12:47 UTC, mariolenz commented on tests/sanity/ignore-2.14.txt
> -plugins/modules/appliance_infraprofile_configs.py pep8!skip
breaking

2024-08-17 12:48 UTC, mariolenz commented
Additionally, should we also backport #516 while we're at it?

2024-08-17 13:17 UTC, mikemorency commented
516 was added after the 4.0.0 release, does that matter? It's just a readme change so I'm guessing we may as well include it?

2024-08-17 13:17 UTC, mikemorency commented on tests/sanity/ignore-2.14.txt
> -plugins/modules/appliance_infraprofile_configs.py pep8!skip
Ah, right. I'll back these out

2024-08-17 13:40 UTC, mariolenz commented
> 516 was added after the 4.0.0 release, does that matter? It's just a readme change so I'm guessing we may as well include it?

I think it would be a good idea, otherwise I wouldn't have suggested is ;-)

But maybe @bardielle or @machacekondra think differently. Personally, I don't think this is a problem.

2024-08-19 17:26 UTC, mikemorency commented
OK, included 516 and removed the breaking change!

2024-08-20 16:01 UTC, mariolenz approved these changes
LGTM

2024-08-20 19:15 UTC, machacekondra commented
So why not include the commits using the label?

2024-08-20 19:49 UTC, mikemorency commented
i tried the label on two PRs and nothing happened. Maybe I am using it wrong? I applied it to my PRs https://github.com/ansible-collections/vmware.vmware_rest/pull/503 and https://github.com/ansible-collections/vmware.vmware_rest/pull/505

2024-08-21 06:10 UTC, machacekondra commented
> i tried the label on two PRs and nothing happened. Maybe I am using it wrong? I applied it to my PRs #503 and #505

Yeah, seems it's broken for some time: https://github.com/ansible-collections/vmware.vmware_rest/actions/workflows/patchback.yml

2024-08-21 06:11 UTC, machacekondra approved these changes

2024-08-21 13:05 UTC, merged