update readme to match certified content template
ansible-collections/vmware.vmware_rest pull request #522
Opened 2024-08-22 17:02 UTC by mikemorency

##### SUMMARY
Updating README format to match standard template described here https://access.redhat.com/articles/7068606

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
README.md

2024-08-26 17:18 UTC, mariolenz reviewed
I'm not really a Markdown expert, but are those `<br/>`s really necessary? They look a little bit strange to me.

2024-08-26 17:18 UTC, mariolenz commented on README.md
> +<br/>You can also include it in a requirements.yml file and install it with `ansible-galaxy collection install -r requirements.yml`, using the format:
`<br/>`?

2024-08-26 17:18 UTC, mariolenz commented on README.md
> +<br/>Note that if you install the collection from Ansible Galaxy, it will not be upgraded automatically when you upgrade the Ansible package.
`<br/>`?

2024-08-26 17:18 UTC, mariolenz commented on README.md
> +<br/>You can also install a specific version of the collection, for example, if you need to install a different version. Use the following syntax to install version 1.0.0:
`<br/>`?

2024-08-26 17:18 UTC, mariolenz commented on README.md
> +<br/>If a support case cannot be opened with Red Hat and the collection has been obtained either from [Galaxy](https://galaxy.ansible.com/ui/) or [GitHub](https://github.com/ansible-collections/vmwar
`<br/>`?

2024-08-27 17:25 UTC, mariolenz commented
Closing temporarily, will re-open once #524 has been merged to enforce a new "clean" CI run.

2024-08-27 18:19 UTC, mariolenz approved these changes
LGTM

2024-08-28 13:59 UTC, mikemorency commented
Waiting to merge until after https://github.com/ansible-collections/vmware.vmware_rest/pull/525

2024-08-29 15:46 UTC, mariolenz requested changes
> Pull request merge failed: Resource not accessible by integration, You may need to manually rebase your PR and retry.

This looks weird, I don't understand it. Could try to rebase? Maybe this really helps :shrug:

2024-08-30 13:26 UTC, mariolenz approved these changes

2024-08-30 13:43 UTC, merged